### ISSUE TITLE
ASAP Order Time is Incorrect

### ISSUE THREAD

**Issue by djtimca** [tastyigniter/ti-ext-local#43]
**Expected behavior:**
When an order is placed with ASAP, the order time should be one of:

Current time + lead time

or

Nearest Time Slot to Current Time + lead time (I think this is the intended behaviour)

**Actual behavior:**

The time on the order for ASAP seems to be getting pushed out significantly.

**Reproduce steps:**

Location with delivery only, time slots set to 15 minutes, and delivery lead time of 40 minutes.

Placed an ASAP order at 06:04.

Order is received in the system with the Order is ASAP flag set to TRUE (correctly) but the order time shows 08:30.

**Version:**
Beta.26

**Additional Information:**

**Comment by ryanmitchell** [comment]
Whats your opening time and what was the next available time slot?
I think it probably relates to https://github.com/tastyigniter/TastyIgniter/issues/698

**Comment by djtimca** [comment]
I have that location set to open 24 hours. Next available time slot on the cart looks to be correct (ie. I can order for not-ASAP and the first time slot available aligns to the expected lead time).

**Comment by ryanmitchell** [comment]
Hmm ok, doesnt relate then.
Are you using maximum order limiting - any chance the next slot was full already?

**Comment by djtimca** [comment]
Yes - I just tested without maximum order limiting on and it worked fine. There were no orders in queue when I had it set to limited though. I think it is related to the order limiting logic though.
