### ISSUE TITLE
Error given if location rule of -1 (delivery not offered)z

### ISSUE THREAD

**Issue by Zelig880** [tastyigniter/ti-ext-local#44]
**Expected behavior:**
I should be able to add the item on the cart even if it does not reach the minimum delivery value yet (otherwise I am not able to create my cart)

**Actual behavior:**
I get an error when I try to add an item to the cart, if the minimum delivery charge is not set and delivery is NOT offered for other values

**Reproduce steps:**
- set a location with rule a charge 0 above 15£
- set a location rule with a charge of -1 below 15£
- Go on the website and try to add something to the site (an item that is less than 15 $)
- You will get an error showing that the restaurant does not deliver to the place.

**Version:**
3.0.4-beta-27

**Additional Information:**
I have been able to find a workaround, by setting a delivery charge of 5£ for value below the FREE delivery. It seems like that the issue is the use of -1.

video: https://www.loom.com/share/21bc2453d6ca42fb921ab35c4a25cbbe

**Comment by ryanmitchell** [comment]
Hmm - maybe been caused by these changes @sampoyigi ?
https://github.com/tastyigniter/ti-ext-local/pull/38

**Comment by sampoyigi** [comment]
Seems to be related to this instead to tastyigniter/ti-ext-cart#46. I think we shouldn't do the delivery charge check when adding or updating the cart, it should be done on page load to disable the checkout button and redirect on the checkout page.

Or we could allow add/update cart and somehow display a warning to the customer to add more item to enable checkout...

**Comment by sampoyigi** [comment]
Actually, we already have a warning message on the Delivery cart condition so I'll revert the commit to fix this.
