### ISSUE TITLE
Flash message appears when added product price is below the minimum order amount 

### ISSUE THREAD

**Issue by abdelouahedhamdi** [tastyigniter/ti-ext-local#47]
**Expected behavior:**
it should be possible to add a product to cart even if it is below the minimum order amount.

**Actual behavior:**
a flash message (this restaurant cannot deliver to your address)

**Reproduce steps:**
delivery conditions : 
-1 below 10
5 below 15
0 above 20

**Version:**
3.0.4 beta.27

**Comment by PlumbBum** [comment]
@abdelouahedhamdi did you fix this? I'm currently experiencing this bug.
