### ISSUE TITLE
Newsletter email address placeholder text incorrect in footer

### ISSUE THREAD

**Issue by wakey18** [tastyigniter/ti-ext-local#5]
**Expected behavior:**
email address text for newsletter to be shown

**Actual behavior:**
shows "igniter.local::default.label_newsletter_email" in placeholder

**Reproduce steps:**
default install, just look at the footer

**Version:**
latest

**Additional Information:**
just needs language file editing...
`'label_newsletter_email' => 'Enter email address',`

**Comment by sampoyigi** [comment]
Fixed.
