### ISSUE TITLE
Collapse indicator dont match the collapse state of categories

### ISSUE THREAD

**Issue by danielang** [tastyigniter/ti-ext-local#53]
**Actual behavior:**
Set `Collapse after how many categories` of the `Local Menu Component` to something less then `5`.
![image](https://user-images.githubusercontent.com/6752808/116577892-2bd74b00-a911-11eb-807d-324d5879d692.png)

**Reproduce steps:**
Set `Collapse after how many categories` of the `Local Menu Component` to something different then `5`.

**Version:**
TI: v3.0.4-beta.27
Local: v1.10.0

**Fix**
Use `$menuCollapseCategoriesAfter` instead of `5` in the `grouped.blade.php` on line `11`

**Comment by ryanmitchell** [comment]
Your commit looks good as a fix.. Open a PR! Thanks.

**Comment by danielang** [comment]
PR is created :)
