### ISSUE TITLE
Reviews extension admin panel is doing the opposite of what it should be

### ISSUE THREAD

**Issue by sbaptista11** [tastyigniter/ti-ext-local#65]
**Expected behavior:**
On label for approving reviews should show "Approved" and Off label should show "Pending Approval". One star reviews should translate to "Bad" and five star reviews should translate to "Excellent"

**Actual behavior:**
On label for approving reviews is set to show "Pending Approval" and Off label is set to show "Approved". One star reviews translate to "Excellent" and five star reviews translate to "Bad"

**Reproduce steps:**
It's the same way on the TastyIgniter Demo page so I assume it came that way on install

**Version:**
Latest Version

**Additional Information:**
(Additional information, if any)

**Comment by ryanmitchell** [comment]
I assume you mena on the graphs? If so I've fixed that.

I dont think we'll change the label - it works ok as is.

**Comment by sampoyigi** [comment]
Also can't reproduce this. Can you confirm which part of the system is affected, admin or frontend?
