### ISSUE TITLE
Info section error after updating to latest tastyigniter develop

### ISSUE THREAD

**Issue by tlloydukdev** [tastyigniter/ti-ext-local#7]
**Expected behavior:**
Info section loads

**Actual behavior:**
Info section errors with `Call to undefined method Igniter\Local\Classes\Location::lastOrderTime()`

**Reproduce steps:**
Activate the local extension, go to View Menu, select Info sub-section

**Version:**
Latest develop

**Additional Information:**
This seems to be related to this commit https://github.com/tastyigniter/ti-ext-local/commit/4b3e5389a3ceed6326d7980985de03a5a47c1f9e

**Comment by sampoyigi** [comment]
This also related to https://github.com/tastyigniter/flame/commit/364412751658a17de453910af5518c2850595da1

The lastOrderTime() method has been removed in the dev branch

**Comment by tlloydukdev** [comment]
Yep, I have this commit too

**Comment by tlloydukdev** [comment]
Confirmed, thanks
