### ISSUE TITLE
[Bug]: Fix typo in docs localBox -> localList 

### ISSUE THREAD

**Issue by mahmoudawadeen** [tastyigniter/ti-ext-local#75]
### What happened?

Typo in docs, should be localList

![Screenshot 2022-03-16 at 09 37 58](https://user-images.githubusercontent.com/6750786/158549846-4e4cf7ac-e43e-466f-9eb5-7ac593e69229.png)

### What did you expect to happen?

I tried to open a pull request for this but got permission denied when pushing my branch.

### Version

3.2.x

**Comment by sampoyigi** [comment]
Fixed! Thanks!
