### ISSUE TITLE
Timeslot change should update menus

### ISSUE THREAD

**Issue by ryanmitchell** [tastyigniter/ti-ext-local#8]
**Expected behavior:**
If menu items are in mealtimes that is unavailable in the selected time slot, they should become available when the time slot changes to one they are available in.

**Actual behavior:**
The menu item only becomes available with a page refresh.

**Reproduce steps:**
Set a menu item to a mealtime (e.g. dinner).
Set the scheduled time to 8.30am
The menu item wont be available
Set the time to 8pm, the menu item still wont be available
Refresh the page, the item is available

**Version:**
3 latest beta

**Additional Information:**
The simplest solution would be to do a location.refresh in done() in onSubmitForm() of local.timeslot.js

**Comment by sampoyigi** [comment]
I'll accept a PR for a location.refresh as suggested.

**Comment by ryanmitchell** [comment]
No problem: https://github.com/tastyigniter/ti-ext-local/compare/master...ryanmitchell:patch-2

**Comment by sampoyigi** [comment]
Resolved.
