### ISSUE TITLE
[Bug]: full address bug

### ISSUE THREAD

**Issue by diverds1992** [tastyigniter/ti-ext-local#85]
### What happened?

After the latest update the localbox search nearby is working with full address instead of postcode.
which works fine when the customers is in the same city as the restaurant. But when the customers address is in another city then the restaurant, the customers get the error message "We do not have any local restaurant near you." When the customers use (address, city) it works a bit better. but sometimes they need to use ( address, postcode, city). 

### What did you expect to happen?

...

### Version

3.5.x

**Comment by sampoyigi** [comment]
Can you verify that this wasn't the behaviour prior to the most recent update? The last update's sole changes would result in a "missing street address" error message rather than the message "We do not have any local restaurants near you."
