### ISSUE TITLE
Timepicker does not select chosen time

### ISSUE THREAD

**Issue by tlloydukdev** [tastyigniter/ti-ext-local#9]
**Expected behavior:**
After setting a timeslot, when I go change it again, the previously selected time should be pre-selected

**Actual behavior:**
The time selector always says "Select time"

**Reproduce steps:**
N/A as above

**Version:**
latest develop

**Additional Information:**
assets/js/local.timeslot.js line 90 should be `selectedHour === index` not `selectedHour === hour`

**Comment by sampoyigi** [comment]
Do you think you could submit a quick PR for this?

**Comment by sampoyigi** [comment]
Also related #8

**Comment by tlloydukdev** [comment]
Yes sure, I’ll get this sorted 👍🏼 


Sent from Yahoo Mail for iPhone


On Sunday, June 21, 2020, 8:31 pm, Sam Poyigi <notifications@github.com> wrote:




Do you think you could submit a quick PR for this?

**Comment by tlloydukdev** [comment]
@sampoyigi PR - https://github.com/tastyigniter/ti-ext-local/pull/13/commits/8c56fcfc6a17e2df5ea1c1793ba01594a1254b55

**Comment by sampoyigi** [comment]
Merged!
