### ISSUE TITLE
[Bug]: Lower case for area labels 

### ISSUE THREAD

**Issue by antoniozh** [tastyigniter/ti-ext-local#90]
### What happened?

The getAreaConditionLabels method in the Info.php returns all strings case lowered. I don't think that this should  be the expected behaviour, since in some languages every noun is capitalized (e.g German). 

### What did you expect to happen?

Area conditions to be shown with upper case characters if intended in the localization  

### Version

3.x

### What browser are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by sampoyigi** [comment]
Feel free to open a pull request with the changes
